os:
  - linux
services:
  - docker
language: javascript
node_js:
  - "4.5.0"
sudo: false
cache:
  directories:
    - node
    - node_modules
env:
  - NODE_VERSION=4.5.0
before_install:
  - nvm install $NODE_VERSION
  - npm install -g bower
  - node -v
  - npm -v
  - bower -v
install: gulp install
script:
  - gulp test
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
